name: Expression
on:
  workflow_dispatch:
    inputs:
      edad:
        description: 'Edad'
        required: true
        type: integer
      nombre:
        description: 'Nombre'
        required: true
        default: 'Juan' # Establece un valor predeterminado
        type: string
jobs:
  mayor:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.edad >= 18 }}
    steps:
      - name: Correr script
        run: echo ${{ github.event.inputs.nombre }} es mayor de edad

  menor:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.edad < 18 }}
    steps:
      - name: Correr script
        run: echo ${{ github.event.inputs.nombre }} es menor de edad

