# This is a basic workflow to help you get started with Actions

name: Expresiones
run-name: ¡Estoy aprendiendo a usar Expresiones!
on:
  workflow_dispatch:
    inputs:
      edad:
        description: 'Edad'
        required: true
        type: integer
      nombre:
        description: 'Tu nombre'
        required: true
        default: 'Juan'
        type: string
      dni:
        description: 'dni'
        required: true
        default: '7600000'
jobs:
  mayor:
    if: ${{ inputs.edad >= 18 }} 
    runs-on: ubuntu-latest
    steps:
      - name: Correr script
        run: echo ${{ inputs.nombre }} es mayor de edad
  menor:
    if: ${{ inputs.edad < 18 }} 
    runs-on: ubuntu-latest
    steps:
      - name: Correr script
        run: echo ${{ inputs.nombre }} es menor de edad
        
  validar_dni:
    runs-on: ubuntu-latest

    steps:
    - name: Verificar Input
      id: input_validation
      run: |
        input_value="${{ inputs.dni }}"
        if [[ ${#input_value} -ge 7 ]]; then
          echo "El input '${input_value}' tiene al menos 7 dígitos."
          echo "::set-output name=input_valid::true"
        else
          echo "El input '${input_value}' no tiene al menos 7 dígitos."
          echo "::set-output name=input_valid::false"
        fi

    - name: Utilizar el resultado de la verificación
      run: |
        if [[ "${{ steps.input_validation.outputs.input_valid }}" == 'true' ]]; then
          echo "Realizar acciones adicionales aquí porque el input tiene al menos 7 dígitos."
        else
          echo "No realizar acciones adicionales porque el input no tiene al menos 7 dígitos."
        fi
  
