name: Expresiones
on:
  workflow_dispatch:
    inputs:
      edad:
        description: 'Edad'
        required: true
        type: integer
      nombre:
        description: 'Tu nombre'
        required: true
        default: 'Juan'
        type: string
      dni:
        description: 'dni'
        required: true
        default: '7600000'
jobs:
  mayor:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.edad >= 18 }}
    steps:
      - name: Correr script
        run: echo ${{ github.event.inputs.nombre }} es mayor de edad

  menor:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.edad < 18 }}
    steps:
      - name: Correr script
        run: echo ${{ github.event.inputs.nombre }} es menor de edad

  validar_dni:
    runs-on: ubuntu-latest
    steps:
      - name: Verificar dni
        id: input_validation
        run: |
          input_value="${{ github.event.inputs.dni }}"
          if [[ ${#input_value} -ge 7 ]]; then
            echo "El input '${input_value}' tiene al menos 7 dígitos."
            echo "::set-output name=input_valid::true"
          else
            echo "El input '${input_value}' no tiene al menos 7 dígitos."
            echo "::set-output name=input_valid::false"
          fi

      - name: Respuesta dni validado
        if: steps.input_validation.outputs.input_valid == 'true'
        run: |
          echo "Realizar acciones adicionales aquí porque el input tiene al menos 7 dígitos."

